---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	supervisor(supervisor)
	querier(querier)
	researcher(researcher)
	summarizer(summarizer)
	__end__([<p>__end__</p>]):::last
	__start__ --> supervisor;
	querier --> supervisor;
	researcher --> supervisor;
	summarizer --> __end__;
	supervisor -.-> querier;
	supervisor -.-> researcher;
	supervisor -.-> summarizer;
	supervisor -. &nbsp;FINISH&nbsp; .-> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
