"""
Package Installer Utility

This module provides functionality to automatically install Python packages required to run code generated by an agent. 
It identifies missing packages based on the imports in the provided code, checks the current environment for already 
installed packages, and installs the missing ones using pip.

Functions:
	- get_installed_packages() -> Set[str]:
		Retrieves a set of installed packages in the current Python environment.

	- install_package(packages: str) -> Dict[str, bool]:
		Installs the specified packages using pip and returns a dictionary indicating the installation status.

	- install_missing_packages(required_packages: Set[str]) -> Dict[str, bool]:
		Installs missing packages from a given set of required packages and returns their installation status.

	- extract_import(code: str) -> Set[str]:
		Extracts package names from the import statements in the provided code and returns them as a set.
"""

import subprocess
import sys
from typing import Dict, Set
import re


def get_installed_packages() -> Set[str]:
    """
    Get a list of installed packages in the current environment.

    Returns:
        A set of installed package names.
    """
    installed_packages = set()
    try:
        import pkg_resources
        installed_packages = {pkg.key for pkg in pkg_resources.working_set}
    except ImportError:
        pass
    return installed_packages


def install_package(packages) -> Dict[str, bool]:
    """
    Install the specified packages using pip.
    Args:
		packages: A list of package names to install.
    Returns:
		A dictionary with package names as keys and installation status as values.
	"""
    result = {}
    for package in packages:
        try:
            subprocess.check_call(
                [sys.executable, '-m', 'pip', 'install', package]
            )
            result[package] = True
        except subprocess.CalledProcessError:
            result[package] = False
    return result

def install_missing_packages(required_packages: Set[str]) -> Dict[str, bool]:
    """
    Install missing packages in the current environment.

    Args:
        required_packages: A set of required package names.

    Returns:
        A dictionary with package names as keys and installation status as values.
    """
    print(required_packages)
    installed_packages = get_installed_packages()
    missing_packages = required_packages - installed_packages
    print(missing_packages)
    return install_package(missing_packages) if missing_packages else {}

def extract_import(code:str) -> Set[str]:
    """
    Extract the package names from the given code.
	Args:
		code: A string containing the code to analyze.
    """
    import_pattern = re.compile(
        r'^\s*(?:from\s+([\w.]+)\s+import|import\s+([\w.]+))',
        re.MULTILINE
    )
    matches = import_pattern.finditer(code)
    packages = set()

    for match in matches:
        # print(match)
        package = match.group(1) or match.group(2)
        # print(package)
        if '.' in package:
            base_package = package.split('.')[0]
        else:
            base_package = package
        # print(base_package)
        if base_package not in sys.stdlib_module_names:
            packages.add(base_package)

    return packages
def get_code_from_file(file_path: str) -> str:
	"""
	Read the content of the file at the specified path.

	Args:
		file_path: The path to the file.

	Returns:
		The content of the file as a string.
	"""
	with open(file_path, 'r') as file:
		return file.read()
if __name__ == "__main__":
	# Example usage
	# print(get_code_from_file("scraper.py"))
	# print(extract_import(get_code_from_file("scraper.py")))
	# print(install_missing_packages(extract_import(get_code_from_file("scraper.py"))))